version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - user-service
      - document-service
    networks:
      - microservices-network

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - microservices-network

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    networks:
      - microservices-network

  document-service:
    build:
      context: ./document
      dockerfile: Dockerfile
    volumes:
      - ./document/uploads:/app/uploads
    ports:
      - '3003:3003'
    networks:
      - microservices-network
      

networks:
  microservices-network:
    driver: bridge
