version: '3.3'

services:
 
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: document
      POSTGRES_USER: document
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432" # Expose PostgreSQL port to the host
      
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
       

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ct.pankaj@gmail.com
      PGADMIN_DEFAULT_PASSWORD: strongpassword
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8081:81" # Access pgAdmin on http://localhost:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
